apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pysfs4bmz-nodejs
  janus-idp.io/tekton: pysfs4bmz-nodejs
  backstage.io/kubernetes-id: pysfs4bmz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pysfs4bmz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
