apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pysfs4bmz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pysfs4bmz-nodejs 
  name: pysfs4bmz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pysfs4bmz-nodejs 
